export const buttons = [
	{ value: "%", className: "text-gray bg-softWhite hover:bg-softWhiteHover" },
	{ value: "√", className: "text-gray bg-softWhite hover:bg-softWhiteHover" },
	{ value: "CE", className: "text-gray bg-softWhite hover:bg-softWhiteHover" },
	{ value: "C", className: "text-white bg-darkBlue hover:bg-black" },
	{ value: "7", className: "text-gray bg-lightGray hover:bg-lightGrayHover" },
	{ value: "8", className: "text-gray bg-lightGray hover:bg-lightGrayHover" },
	{ value: "9", className: "text-gray bg-lightGray hover:bg-lightGrayHover" },
	{ value: "-", className: "text-white bg-red hover:bg-redHover" },
	{ value: "4", className: "text-gray bg-lightGray hover:bg-lightGrayHover" },
	{ value: "5", className: "text-gray bg-lightGray hover:bg-lightGrayHover" },
	{ value: "6", className: "text-gray bg-lightGray hover:bg-lightGrayHover" },
	{ value: "÷", className: "text-white bg-blue hover:bg-blueHover" },
	{ value: "1", className: "text-gray bg-lightGray hover:bg-lightGrayHover" },
	{ value: "2", className: "text-gray bg-lightGray hover:bg-lightGrayHover" },
	{ value: "3", className: "text-gray bg-lightGray hover:bg-lightGrayHover" },
	{ value: "×", className: "text-white bg-yellow hover:bg-yellowHover" },
	{ value: ".", className: "text-gray bg-lightGray hover:bg-lightGrayHover" },
	{ value: "0", className: "text-gray bg-lightGray hover:bg-lightGrayHover" },
	{ value: "=", className: "text-gray bg-softWhite hover:bg-softWhiteHover" },
	{ value: "+", className: "text-white bg-green hover:bg-greenHover" },
];
